name: ticketing_system
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  gettext: ^1.2.0
  get: ^4.3.8
  dio: ^5.4.3+1
  google_fonts: ^6.2.1
  flutter_donation_buttons: ^0.4.10
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
